### ISSUE TITLE
es_ES-translated-and-google.csv da error?

### ISSUE THREAD

**Issue by toniyecla** [eusonlito/magento2-language-es_es#1]
comandos para reproducir el error:

`bin/magento i18n:pack --mode=replace -d vendor/eusonlito/magento2-language-es_es/es_ES-translated-and-google.csv . es_ES`

Successfully saved es_ES language package.

`bin/magento setup:static-content:deploy es_ES`

File "/i18n/es_ES.csv" does not exist>

**Comment by toniyecla** [comment]
parece relacionado con magento 2.0.5: https://github.com/magento/magento2/issues/3592

solucíon (temporal)

ln -s /path_to_magento2/i18n /

bin/magento setup:static-content:deploy es_ES
Requested languages: es_ES
=== frontend -> Magento/blank -> es_ES ===
.......................................................................................................................................................................................................................................................................................................

**Comment by eusonlito** [comment]
Ok, veo, yo uso la 2.0.4 sin problema.

Esperaré un poco a ver si lo solucionan y sino añado una nota en el README.

Gracias!
