### ISSUE TITLE
Magento 2.1 y dependencias

### ISSUE THREAD

**Issue by rmontagud** [eusonlito/magento2-language-es_es#3]
Cuando intento instalar el pack con composer hay un problema de dependencias, pero me llama la atención que no le cuele porque veo en el composer.json del repositorio que hay un comodín (100.*) ¿Quizá usando "^100.0"?

![image](https://cloud.githubusercontent.com/assets/21723/18718464/edbb8dec-8023-11e6-9b38-b05afb8856b8.png)

**Comment by eusonlito** [comment]
Prueba a añadirlo a composer con:

```
composer require eusonlito/magento2-language-es_es dev-master
```

**Comment by rmontagud** [comment]
Vale, con esto he podido instalar el paquete de composer pero parece que i18n:pack intenta crear un directorio donde no debe o que no existe por algún módulo que no tengo instalado porque exportando los strings de mi instalación e instalandolo como es_ES sí que funciona

**Comment by eusonlito** [comment]
Sí, puede ser, este paquete incluye todos las extensiones de Magento, con lo cual si se decide instalarlo de manera "parcial" es probable que el sistema intente copiar traducciones en carpetas que no existen. Supongo que será algo a mejorar en Magento ya que no tiene sentido publicar e instalar las traducciones por separado para cada componente.

**Comment by rmontagud** [comment]
He descubierto por qué es, sigue siendo un problema de la herramienta que insiste en escribir contra el raíz del sistema cuando no puede identificar a qué modulo pertenece
Solucion: (muy a mi pesar) Ejecutar php bin/magento i18n:pack como root
Referencia: https://github.com/magento/magento2/issues/6260

**Comment by eusonlito** [comment]
:+1:
