### ISSUE TITLE
Palabras en Aleman?

### ISSUE THREAD

**Issue by cyrusnimda** [eusonlito/magento2-language-es_es#4]
El boton de guardar en la parte de administracion, me sale en Aleman, y a parte hay algunas cosillas que en la version 2.1 no estan traducidas, se aceptan pull request?

Pego la parte del boton en aleman.

./vendor/eusonlito/magento2-language-es_es/es_ES-translated.csv:"Save Config","Konfiguration speichern","module","Magento_Config"
./vendor/eusonlito/magento2-language-es_es/es_ES-translated-and-google.csv:"Save Config","Konfiguration speichern","module","Magento_Config"
./vendor/eusonlito/magento2-language-es_es/es_ES.csv:"Save Config","Konfiguration speichern","module","Magento_Config"
./vendor/magento/module-config/i18n/es_ES.csv:"Save Config","Konfiguration speichern"

**Comment by eusonlito** [comment]
Sí, claro, se aceptan pull requests.

Es raro, supongo que será algún error inicial de la plataforma de traducción que contenía las cadenas iniciales.

**Comment by eusonlito** [comment]
Hace ya un tiempo de esto :D

He actualizado de nuevo las traducciones y me he encontrado con ellas.

Habría que actualizarlas en Crowdin para evitar que se importen de nuevo con cada actualización.

Saludos!
